### ISSUE TITLE
New upgrade to 3.8 giving error in robyn_inputs

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#520] opened 2022-10-28 13:33 UTC
Hi Team,

I have upgraded to the new Robyn 3.8 version and getting the below error:
<img width="498" alt="Screen Shot 2022-10-28 at 9 30 11 AM" src="https://user-images.githubusercontent.com/89505409/198613393-31466897-8f24-4b27-9ba4-c016accd610d.png">

**Comment by laresbernardo** [comment] 2022-10-28 15:12
Thanks for reporting this bug @virithavanama I've updated main branch, can you please update and re-try?

**Comment by virithavanama** [comment] 2022-10-28 15:28
Thanks, @laresbernardo for the prompt fix :)
Now I get a new issue when running robyn_run:
<img width="733" alt="Screen Shot 2022-10-28 at 11 26 56 AM" src="https://user-images.githubusercontent.com/89505409/198675263-bd195897-f4ad-453d-bd50-b85d5884e3e6.png">

**Comment by laresbernardo** [comment] 2022-10-28 15:31
Can you please share a reproducible example as I can't seem to be able to reproduce this one?

**Comment by DpfStat** [comment] 2022-11-01 05:32
Same issue with 3.8.0 for running robyn_run. If use the same data set with 3.7.2, no error.

**Comment by firatfrkn** [comment] 2022-11-01 08:27
The same issue I am having 
![Screenshot 2022-11-01 112633](https://user-images.githubusercontent.com/96492785/199190939-c7daca5c-2b36-45be-96a3-ab682d418513.png)

**Comment by gufengzhou** [comment] 2022-11-01 08:32
We can't reproduce the same error. Could you please share an anonymised dataset for us to debug. thanks

**Comment by firatfrkn** [comment] 2022-11-01 12:58
Thank you so much. Could you please tell me briefly where was the bug. I’ve
been trying to solve as well. Is that because
 nrmse.collect<- unlist(laplly(doparcollect,function(x) x$nrmse))

?


Вт, 1 нояб. 2022 г. в 3:54 PM, gufengzhou ***@***.***>:

**Comment by firatfrkn** [comment] 2022-11-01 13:15
thanks a lot. It works for me now

**Comment by gufengzhou** [comment] 2022-11-01 13:22
cool thanks for confirming. you can check the fix detail in the commit [here](https://github.com/facebookexperimental/Robyn/commit/4f81ffc70da029fd75b9de61a64d4b0d571ff458)

**Comment by AruunnAnanda** [comment] 2022-11-01 13:57
@gufengzhou I still have the same problem after updating to v3.8.1. To update I ran the command - Robyn::robyn_update()
![image](https://user-images.githubusercontent.com/107944288/199250454-d56ef9d0-7021-48bc-ac38-f8a2fe83388b.png)

**Comment by gufengzhou** [comment] 2022-11-01 14:20
strange. have you checked `packageVersion("Robyn")` that's v3.8.1 and restarted the R session?

**Comment by AruunnAnanda** [comment] 2022-11-01 14:23
@gufengzhou Yes, I did. 

This time the error is - **Error in {: task 1 failed - "non-numeric argument to binary operator"**

This error is different than the last time. I'm attaching the last time error here. 
![image](https://user-images.githubusercontent.com/107944288/199256130-6024bcda-2d0b-404f-88a6-66213499946a.png)

**Comment by gufengzhou** [comment] 2022-11-01 14:26
Please provide your dataset anonymised and your model specification in robyn_inputs() for debugging. you can send it to gufeng@meta.com

**Comment by gufengzhou** [comment] 2022-11-02 05:11
Hey @AruunnAnanda , I managed to reproduce your error and just pushed a fix. Could you please update and retest. thanks

**Comment by AruunnAnanda** [comment] 2022-11-02 08:07
Hey @gufengzhou, I unfortunately still have the same error. 

If I don't use calibration as an input the model **"RUNS FINE"**. 

If I use start using calibration as an input the model **throws an error**

**Comment by gufengzhou** [comment] 2022-11-02 10:02
ok that's an important information missing that you used calibration. I'll check and get back.

**Comment by gufengzhou** [comment] 2022-11-02 12:40
@AruunnAnanda Please update and check

**Comment by AruunnAnanda** [comment] 2022-11-02 17:32
@gufengzhou I still have the same issue :(  

I sent you the anonymised data via email to replicate and debug.

**Comment by gufengzhou** [comment] 2022-11-04 08:14
thanks for the data. I've just pushed another fix and it runs on my macbook. please update and try

**Comment by virithavanama** [comment] 2022-11-04 15:13
Thanks for the bug fixes. robyn_inputs issue is fixed for me too! But now having an issue with robyn_outputs:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/89505409/200009849-6865c3a4-7ff5-4429-bfe9-b4c9f827790a.png">

**Comment by gufengzhou** [comment] 2022-11-04 15:16
there's been some fixes since then. can you update the package incl. dependencies, restart R and retry please?

**Comment by gufengzhou** [comment] 2022-11-08 11:29
This should be fixed with the latest commits. Please update and check

**Comment by gufengzhou** [comment] 2022-12-21 03:54
Please reopen if issue reoccurs.

**Closed by gufengzhou** 2022-12-21 03:54 UTC
Labels: bug
