### ISSUE TITLE
How to obtain data for ROI curves?

### ISSUE THREAD

**Issue by ElijahHoff** [facebookexperimental/Robyn#566] opened 2022-12-13 21:43 UTC
## Project Robyn

Hi everyone, how to plot and / or obtain corresponding data? It should display maximum and optimal spend this is not the same as response marketing curves. Thanks

**Comment by gufengzhou** [comment] 2022-12-21 04:14
hey, not sure what you mean. Please include reproducible examples for us to debug and/or give advices.

**Comment by michellegrushkometa** [comment] 2023-03-07 15:29
Closing this ticket because we haven’t had any replies. Feel free to re-open if the issue persists.

**Closed by michellegrushkometa** 2023-03-07 15:29 UTC
