### ISSUE TITLE
Cannot plot model onepager with ts_validation = False with "non-numeric argument to mathematical function" error

### ISSUE THREAD

**Issue by rupatrawut** [facebookexperimental/Robyn#946] opened 2024-03-28 04:44 UTC
## Describe issue
If I train Robyn model with `ts_validation` set to `False`, everything looks fine in training phrase. I got all the output such as pareto_aggregated.csv, etc without problem. 

However, when calling `robyn_outputs` api via plumber, I got error message in robyn_log file as below:

> >> Plotting 20 selected models on 7 cores...
> |                                                                            
> |                                                                      |   0%Failed exporting results, but returned model results anyways:
> Error in {: task 1 failed - "non-numeric argument to mathematical function"

I also try this function but return following error.
```
#write one pager to specified location
load_onepager(sol='1_5_1', write=True, InputJson=InputCollect, OutputJson=OutputCollect, path=output_folder)
```

> ----> [4](vscode-notebook-cell:?execution_count=37&line=4) load_onepager(sol='1_5_1', write=True, InputJson=InputCollect, OutputJson=OutputCollect, path=output_folder)
> 
> File [c:\Users\rupatrawut\workspace\ml-marketing-mix-modeling\ml_mmm_robyn\robyn_api\python_helper.py:263](file:///C:/Users/rupatrawut/workspace/ml-marketing-mix-modeling/ml_mmm_robyn/robyn_api/python_helper.py:263), in load_onepager(InputJson, OutputJson, path, sol, top_pareto, write, max_size)
>     [261](file:///C:/Users/rupatrawut/workspace/ml-marketing-mix-modeling/ml_mmm_robyn/robyn_api/python_helper.py:261) sol_id = sol
>     [262](file:///C:/Users/rupatrawut/workspace/ml-marketing-mix-modeling/ml_mmm_robyn/robyn_api/python_helper.py:262) onepager = load_modeldata(sol_id,InputJson=InputJson,OutputJson=OutputJson)
> --> [263](file:///C:/Users/rupatrawut/workspace/ml-marketing-mix-modeling/ml_mmm_robyn/robyn_api/python_helper.py:263) image_data = binascii.unhexlify("".join(onepager))
>     [264](file:///C:/Users/rupatrawut/workspace/ml-marketing-mix-modeling/ml_mmm_robyn/robyn_api/python_helper.py:264) if(write==True):
>     [265](file:///C:/Users/rupatrawut/workspace/ml-marketing-mix-modeling/ml_mmm_robyn/robyn_api/python_helper.py:265)     writefile(datset=image_data,path=path,sol_id=sol_id)
> 
> Error: Odd-length string

**Please note that the code can be ran without any issues, when ts_validation = True.**

## Environment & Robyn version
Robyn version: '3.10.5.9014'
R version: 4.3.2

Thank you for your support :)

**Comment by yu-ya-tanaka** [comment] 2024-04-24 16:07
Hi, I reproduced the same error on my env with setting ts_validation = False.  Will check later and get back to you.

**Comment by rupatrawut** [comment] 2024-04-25 02:38
@yu-ya-tanaka  Thank you :) Please keep me posted.

Another question, once we get the best range of hyperparameter when running ts_val = TRUE, should we train 100% of data using ts_val = FALSE? And insights presented in onepager (e.g., ROI, effect share, decomposition impact) are calculated from training period only or total data point?

**Comment by gufengzhou** [comment] 2024-04-25 06:28
For most usecases, I'd recommend to ts_validation = FALSE. Most onepager numbers are based on the entire modeling window. The training/val/test split is only for time series validation purpose. I'll let Yuya to help you with the bug.

**Comment by yu-ya-tanaka** [comment] 2024-05-02 16:53
Hi @rupatrawut , I have found the cause, there is a problem with the API endpoint and we are fixing it now. The fix will be completed by the end of next week.

**Comment by rupatrawut** [comment] 2024-05-03 03:00
Hi @yu-ya-tanaka. Noted with thanks :)

**Comment by yu-ya-tanaka** [comment] 2024-05-07 07:00
Hi @rupatrawut , We fixed bug in the API endpoint file and merged updates to the main branch. Please use the latest version of endpoint file. Thanks,
https://github.com/facebookexperimental/Robyn/tree/main/robyn_api

**Comment by rupatrawut** [comment] 2024-05-07 09:43
Hi @yu-ya-tanaka Many thanks :)

**Closed** 2024-05-07 10:51 UTC
