### ISSUE TITLE
Error importing JSON Robyn Refresh

### ISSUE THREAD

**Issue by jkngale** [facebookexperimental/Robyn#711] opened 2023-04-27 09:12 UTC
## Describe issue
I tried to refresh robyn's model with new data and got an error when refreshing even that the model is imported correctly. It appears to search for an empty model even that the model is imported and recreated in the same step.

## Provide reproducible example
json_file <- gsub(" ","",paste(plot_folder,"RobynModel-2_339_1.json", sep=""))
#"MMM/output/Robyn_outputs/Robyn_202304141255_init/RobynModel-2_339_1.json"

RobynRefresh <- robyn_refresh(
  json_file = json_file, #json_file,
  dt_input = df_weekly,
  dt_holidays = dt_prophet_holidays,
  refresh_steps = 1,
  refresh_iters = 20,
  refresh_trials = 1,
  ts_validation = FALSE
)

### Ouput in the log
>>> Recreating model 2_339_1
Imported JSON file succesfully: MMM/output/Robyn_outputs/Robyn_202304141255_init/RobynModel-2_339_1.json
Input 'window_end' is adapted to the closest date contained in input data: 2023-03-16
>> Running feature engineering...
NOTE: potential improvement on splitting channels for better exposure fitting. Threshold (Minimum R2) = 0.8 
  Check: InputCollect$plotNLSCollect outputs
  Weak relationship for: "Paid_BingAds_Imp", "Paid_GoogleAds_Shopping_ES_Mesas_Imp", "Paid_GoogleAds_Text_Generic_Imp"and their spend
Input data has 170 weeks in total: 2019-12-30 to 2023-03-16
Initial model is built on rolling window of 170 week: 2019-12-30 to 2023-03-16
Successfully recreated model ID: 2_339_1
 **Error in robyn_read(filename, quiet = TRUE) (MMM.R#361): JSON file can't be imported: MMM/output/Robyn_outputs/RobynModel-.json**

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: `packageVersion("Robyn")` --> ‘3.9.0’
- R version (Please, check and share: `sessionInfo()` or `R.version$version.string`) --> "R version 4.2.2 (2022-10-31 ucrt)"

**Comment by laresbernardo** [comment] 2023-04-27 13:17
Hi @jkngale thanks for reporting.
Noticed you're using version 3.9.0. Would you mind testing with the latest dev version (>=3.10.3.9000)? **I'm not able to reproduce your error**, which actually doesn't make much sense given, as you mentioned, that it created the original model correctly. 
I also noticed from the error that: 
- The path it is trying is missing the `Robyn_202304141255_init` folder
- The JSON file doesn't contain the model ID: `RobynModel-.json`

**Comment by laresbernardo** [comment] 2023-05-08 17:04
Hi! I don't have a Windows to test but it should be exactly the same behaviour. Would you mind sharing a reproducible example (zip folder with all the structure - you can keep the json and data files only) and the code to replicate the error? Thanks.

**Comment by AngelLopezSanz** [comment] 2023-05-31 07:15
Hi @laresbernardo. I could fix that function in my side, but running all the code was not easy for me and multiple errors appeared. Did you have the chance to test it?
By the way, I'm on mac.
@jkngale did you find a solution? I need to recover a model and currently I cannot...

**Comment by banalytics** [comment] 2023-07-16 07:48
@laresbernardo I am running into the same issue (Mac) with the newest version still. I think came to the same conclusion as @AngelLopezSanz on where the issue lies. Fixing it however requires writing custom functions that I would run instead of the package provided functions.

Are there any plans on fixing? Happy to help.

**Comment by laresbernardo** [comment] 2023-07-16 13:40
Hi! I'll try and take a look later next week and see if there's an easy fix. Sadly I was laid off from Meta a couple of weeks ago and won't continue giving active support to Robyn. Feel free to continue this thread @gufengzhou ;)

**Comment by shuvayan** [comment] 2024-04-24 10:36
Any updates on this ? It has been more than 1 year for this issue and it is still open. I am also facing the same issue now with model refresh, this just defeats the purpose of open sourcing solutions if there is no effort to maintain and fix it.

**Comment by gufengzhou** [comment] 2024-04-26 09:24
this is being handled in your latest issue so i'm closing this. there're many reasons why reply is slowing down. so please have understanding and be fair

**Closed by gufengzhou** 2024-04-26 09:24 UTC
