### ISSUE TITLE
New upgrade to 3.8 gave error to robyn_outputs()

### ISSUE THREAD

**Issue by miaox018** [facebookexperimental/Robyn#536] opened 2022-11-16 19:34 UTC
Hi team,

I recently upgraded the package to 3.8.1 version and gets this error at robyn_outputs() step.

Running Pareto calculations for 40000 models on auto fronts...
Error in `build_longer_spec()`:
! Can't subset columns that don't exist.
✖ Columns 'XXX_XX_XX_X', etc. don't exist.
Run `rlang::last_error()` to see where the error occurred.

Here are things I tried:
Downgraded to cran version but end up having an issue at robyn_run() step, which I saw someone else already opened an issue #531. Ran the demo.R with cran version but it went through. 

Sample data was sent to gufeng. Thanks for looking into this!!

**Comment by gufengzhou** [comment] 2022-11-20 15:24
Thanks for sharing an anonymised dataset for debugging. I can't reproduce your error though. I've tried 500 iterations and 1 trial and all is well. Have you updated the dependencies as well?

**Comment by miaox018** [comment] 2022-11-22 14:05
I've updated the dependencies again but this still occurs, this time is at robyn_run() step. 
Error in `build_longer_spec()`:
! Can't subset columns that don't exist.
✖ Columns xxxx, etc. don't exist.

**Comment by gufengzhou** [comment] 2022-11-22 14:21
Sorry to hear that. We have an assumption now that it might be caused by the pivot_longer() function that melts "long tables", esp. for large iterations. Could you try to run only 1k and see if error still occurs?

BTW we just pushed a fix yesterday to reduce size of output objects (OutputModels & OutputCollect), which should ease some memory-related bugs.

**Comment by miaox018** [comment] 2022-11-22 16:46
I just tried and same issue occurred :( Not sure if this is related but when I re-start the Rstudio, it wasn't able to locate the nevergrad installed. I had to go back to run this: use_virtualenv("r-reticulate", required = TRUE). The code started to run but end up with the same error: 

Input data has 371 days in total: 2021-11-01 to 2022-11-06
Initial model is built on rolling window of 371 day: 2021-11-01 to 2022-11-06
Using geometric adstocking with 52 hyperparameters (52 to iterate + 0 fixed) on 1 core (Windows fallback)
>>> Starting 1 trials with 500 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 1
  |================================================================================================== |  99%
  Finished in 1.91 mins
Error in `build_longer_spec()`:
! Can't subset columns that don't exist.
✖ Columns xxxx, etc. don't exist.
Run `rlang::last_error()` to see where the error occurred.

**Comment by miaox018** [comment] 2022-11-22 18:41
Thanks! I was able to run the robyn_run() step but still had issue with output step:

Using robyn object location: C:/Users/xxxx/Documents/App_MMM_Build
>>> Running Pareto calculations for 500 models on auto fronts...
>> Automatically selected 6 Pareto-fronts to contain at least 100 pareto-optimal models (102)
>> Pareto-Front: 1 [14 models]
 00:00:00 [====                                                   ] 7.14% | 1                                    Error in `dt_transformPlot[, med_select]`:
! Can't subset columns that don't exist.
✖ Column `xxxx` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

**Comment by laresbernardo** [comment] 2022-11-22 18:49
Can you share a reproducible example here so I can try and replicate this issue? It's as if you created `InputCollect` and then for some reason the name of the columns (media variable) change somehow and it doesn't find those variables. Currently, given the error shows, it's crashing while generating the "Spend response curve" in pareto.R, and it doesn't find of your media variables from `InputCollect$all_media`.

**Comment by miaox018** [comment] 2022-11-23 13:56
that was helpful, I actually found the paid_media_vars input is not in the right format. Not sure if this could be included as a precheck process so it's more detectable. But after the change, the code ran through. I'm now increasing the iterations and trials, hopefully it works too! Thanks all for your help here!

**Comment by laresbernardo** [comment] 2022-11-23 15:10
Can you please share the format you passed paid_media_vars initially and how you fixed it to see the difference? And yes, we'll add an additional check for this case to avoid this issue.

**Comment by miaox018** [comment] 2022-11-30 13:42
it was in a data frame with one column only. Once I changed it to ‘unlist(dataframe$colnames)’, I got less warnings at robyn_inputs(), which was a sign already but it was not printing the exact error so it was hard to trace.

**Comment by laresbernardo** [comment] 2022-11-30 14:48
Ok, so checking that these inputs are vectors and not lists should be enough to avoid this specific issue you had? Something like `!is.list(paid_media_vars)` (given `is.vector(list())` is true) should work then?

**Comment by miaox018** [comment] 2022-12-02 13:47
yea or just is.vector() and is.null() would work? if that's the only format it should be??

**Comment by laresbernardo** [comment] 2022-12-02 13:48
I've updated the code to contain these checks. It'd be great if you could check with your lists inputs as you did when you reported this issue and see if you get friendly and easy to understand errors. Also, do close this issue if you consider it's been fixed/improved.

**Comment by gufengzhou** [comment] 2022-12-21 04:08
Please reopen if necessary.

**Closed by gufengzhou** 2022-12-21 04:08 UTC
Labels: bug, enhancement
