### ISSUE TITLE
Adstock values in pareto_media_transform_matrix.csv do not match output of adstock_weibull()

### ISSUE THREAD

**Issue by PhilClarkPhD** [facebookexperimental/Robyn#629] opened 2023-02-26 15:11 UTC
## Describe issue
Adstock_weibull() returns different values depending on how it is called. If called from the Robyn library I get the same values as in the pareto_media_transform_matrix.csv. However, if I copy/paste the adstock_weibull() function in a standalone script and call from there, I get a totally different set of numbers. 

## Provide reproducible example
**example.R** shows difference in adstocked values when adstock_weibull() loaded from Robyn library or from standalone script
**weibull.R** a standalone script containing the adstock_weibull() and .normalize() functions
**paid_media_spend.csv** example dataframe with two columns, *ds* and *spend_var*
**pareto_media_transform_matrix.csv** output from Robyn - for comparison to values obtained in example.R

## Environment & Robyn version
- Robyn version: 3.8.2
- R version 4.2.2

[weibull_issue.zip](https://github.com/facebookexperimental/Robyn/files/10834016/weibull_issue.zip)

**Comment by PhilClarkPhD** [comment] 2023-02-27 17:01
Looks like this issue extends to the saturation_hill() function as well.

The SaturatedMedia output in the pareto_media_transform_matrix.csv is different from the output I get if I call saturation_hill() myself using the AdstockedMedia data from pareto_media_transform_matrix as input.

In the zipped file I have example scripts and data to show what I mean.
[saturation_issue.zip](https://github.com/facebookexperimental/Robyn/files/10842101/saturation_issue.zip)

**Comment by gufengzhou** [comment] 2023-03-07 17:51
If you change this in your example_saturation.R, window_start = '2019-04-01' and round my_saturation and robyn_saturation to 2 digits or so, you'll get the same value. The reason is that robyn_saturation has length of 201 and starts with '2019-04-01'. You'll need to input the same "adstocked" as before to exactly reproduce the result.

**Comment by PhilClarkPhD** [comment] 2023-03-07 21:55
@gufengzhou Thank you! That resolves the saturation issue.

Any word on the adstock issue?

**Comment by gufengzhou** [comment] 2023-03-08 05:40
I get the same results. Can't reproduce your error. In your case, because the scale is very small and shape quite large, meaning that the peak will be at period 1 and afterwards sharp decrease, you can see it in the thetaVecCum in the list output. It basically means almost no decay. Probably not the best to for debugging. Otherwise, adstock is always done on the entire available dataset, regardless of your window, maybe this is the source of difference.

**Comment by laresbernardo** [comment] 2023-05-09 21:24
Closing this task now. Feel free to reach back anytime.

**Closed by laresbernardo** 2023-05-09 21:24 UTC
