### ISSUE TITLE
Error installing dev version in R

### ISSUE THREAD

**Issue by caarolinagil** [facebookexperimental/Robyn#897] opened 2024-01-10 11:18 UTC
## Describe issue
I've tried to install the latest deV version from GitHub but I get the following error:

Downloading GitHub repo facebookexperimental/Robyn@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  no fue posible abrir la URL 'https://api.github.com/repos/facebookexperimental/Robyn/tarball/HEAD'

To install the version, I put this code: remotes::install_github("facebookexperimental/Robyn/R") and I've installed library remotes.

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Check and share Robyn version: actually 3.10.3
- R version (Please, check and share: 4.2.1

**Comment by gufengzhou** [comment] 2024-01-27 03:41
Sorry I can't reproduce your error. Might be OS related. Have you checked this? 

https://github.com/forestgeo/learn/issues/102

Please try goggle the error first

**Comment by gufengzhou** [comment] 2024-02-28 06:48
I see you're running the models already and thus closing this.

**Closed by gufengzhou** 2024-02-28 06:48 UTC
