### ISSUE TITLE
Robyn error while running OutputModels <- code - Error in { :    task 1 failed - "arguments imply differing number of rows: 19, 20"

### ISSUE THREAD

**Issue by richa-makhija** [facebookexperimental/Robyn#619] opened 2023-02-08 16:15 UTC
## Describe issue
My code takes in all the inputs correctly but while running the OutputModels <- code, I get the above error

```
InputCollect_us <- robyn_inputs(
  dt_input = data_orig_us,
  dt_holidays = dt_prophet_holidays,
  date_var = c("date"),
  dep_var = "cust_acquired",
  dep_var_type = "conversion",
  prophet_vars = c("trend", "season", "holiday"),
  prophet_country ="US",
  context_vars = c("if_payday","if_covid","if_holiday","fx","fee_avg","fee_promo_spend", "fx_promo_spend", "us_unemployment_rate", "us_inflation"), 
  paid_media_spends = c("paid_social_s", "paid_search_s", "brand_s", "uac_s", "upper_funnel_s", "houston_s", "all_other_s"),
  paid_media_vars = c("paid_social_i", "paid_search_i", "brand_i", "uac_i", "upper_funnel_s", "houston_s", "all_other_s"),
  ##follow same sequence in spends and vars. if using imp dont add spends again to vars.. if no imp, repeat spend variable
  organic_vars = c(),
  ## can be kpt empty
  factor_vars = c("if_payday","if_covid","if_holiday"), 
  ## category or binary vars
  window_start = "2022-08-15",
  window_end = "2022-12-31",
  adstock = "weibull_cdf" 
  ##geometric is simpler
)
print(InputCollect_us)

################ Set Hyper Parameters ####################

plot_adstock(plot = FALSE)
plot_saturation(plot = FALSE)

##use same ranges
hyperparameters_us <- list(
  paid_social_s_alphas = c(0.5,3),
  paid_social_s_gammas = c(0.3, 1),
  paid_social_s_shapes = c(0.0001, 2),
  paid_social_s_scales = c(0, 0.1),
  
  paid_search_s_alphas = c(0.5, 3),
  paid_search_s_gammas = c(0.3, 1),
  paid_search_s_shapes = c(0.0001, 2),
  paid_search_s_scales = c(0, 0.1),
  
  brand_s_alphas = c(0.5, 3),
  brand_s_gammas = c(0.3, 1),
  brand_s_shapes = c(0.0001, 2),
  brand_s_scales = c(0, 0.1),
  
  uac_s_alphas = c(0.5, 3),
  uac_s_gammas = c(0.3, 1),
  uac_s_shapes = c(0.0001, 2),
  uac_s_scales = c(0, 0.1),
  
  upper_funnel_s_alphas = c(0.5, 3),
  upper_funnel_s_gammas = c(0.3, 1),
  upper_funnel_s_shapes = c(0.0001, 2),
  upper_funnel_s_scales = c(0, 0.1),
  
  houston_s_alphas = c(0.5, 3),
  houston_s_gammas = c(0.3, 1),
  houston_s_shapes = c(0.0001, 2),
  houston_s_scales = c(0, 0.1),
  
  all_other_s_alphas = c(0.5, 3),
  all_other_s_gammas = c(0.3, 1),
  all_other_s_shapes = c(0.0001, 2),
  all_other_s_scales = c(0, 0.1)
)
InputCollect_us <- robyn_inputs(InputCollect = InputCollect_us, hyperparameters = hyperparameters_us)
print(InputCollect_us)

OutputModels_us <- robyn_run(
  InputCollect = InputCollect_us, # feed in all model specification
  # cores = NULL, # default to max available
  # add_penalty_factor = FALSE, # Untested feature. Use with caution.
  lambda_control = lambda_min,
  iterations = 2000, # 2000 recommended for the dummy dataset with no calibration
  trials = 5, # 5 recommended for the dummy dataset
  outputs = FALSE # outputs = FALSE disables direct model output - robyn_outputs()
)
```

**Error:**

```
Input data has 365 days in total: 2022-01-01 to 2022-12-31
Initial model is built on rolling window of 139 day: 2022-08-15 to 2022-12-31
Fitting time series with all available data...
Using weibull_cdf adstocking with 30 hyperparameters (29 to iterate + 1 fixed) on 11 cores
>>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...
  Running trial 1 of 5
  |                                                                                                                                                                                                  |   0%Timing stopped at: 2.284 1.347 1.129
Error in { : 
  task 1 failed - "arguments imply differing number of rows: 19, 20"
In addition: Warning message:
In hyper_collector(InputCollect, hyper_in = InputCollect$hyperparameters,  :
  Provided train_size but ts_validation = FALSE. Time series validation inactive.
```

## Provide reproducible example
Issues are often related to custom input data that is difficult to debug without. If necessary, please modify your data to mask real values and share a dataset that is able to reproduce the issue. Please also share your model configuration and exported JSON files if available.

## Environment & Robyn version
> R.version$version.string
[1] "R version 4.2.2 (2022-10-31)"
> packageVersion("Robyn")
[1] ‘3.9.0’

**Comment by richa-makhija** [comment] 2023-02-08 16:25
Some additional context, my data has range from 1/1/22 - 12/31/22 but I am looking to run this model from 8/15 - 12/31.... If i use the window start and window end as 1/1 - 12/31 then the model works.....

**Comment by dmacoritto** [comment] 2023-03-10 11:05
@Amyhaoming, any updates on that issue ? I am having the same issue when trying to read and reproduce a model made under the 3.7.0 version in the 3.9.0 version.

The error message is the following: 
```
Input data has 1369 days in total: 2019-01-01 to 2022-09-30
Initial model is built on rolling window of 290 day: 2021-12-15 to 2022-09-30
Warning: longer argument not a multiple of length of shorterAttention for loop 1: immediate & carryover decomp don't sum up to total
Timing stopped at: 0.02 0 0.19
Error in { : 
  task 1 failed - "arguments imply differing number of rows: 25, 26"
```

And the traceback 

![image](https://user-images.githubusercontent.com/64702803/224299976-8010b153-c7e9-49bf-baaf-6f3c9b245c94.png)

Not sure what is going on, I have spend some time investigating, but couldn't find the issue.

Thanks for your help

**Comment by gufengzhou** [comment] 2023-03-10 11:55
It looks like you're loading an old model that was built using older version, then recreating using the new version. This might the reason. Esp. Because after 3.9 there's a new hyperparameter train_size that didn't exist before. Can you please rerun your model using the latest package with the narrower ranges as in your old model.

**Comment by dmacoritto** [comment] 2023-03-13 08:09
@gufengzhou, yes it works with the 3.7 version. Nonetheless, I am not sure this is due to the hyperparameter train_size, as it is created automatically if not detected (its value is equal to 1).
Do you mean that all models are not retro-compatible? The ones created in 3.9 will not be compatible with higher versions ?

**Comment by arturodz** [comment] 2023-04-07 23:39
Hi!

I can report I am having the same issue. Interestingly is only happening with one of my clients. I tried others and it ran perfectly fine. I tried different date ranges with no success. I was successful in running robyn back on version 3.7.2 for this client.

**Comment by sahbakn** [comment] 2023-05-11 20:57
@gufengzhou @laresbernardo Can you guys kindly take a look at this bug again? as I mentioned in my previous comment, I am not trying to load a model based on an older version, I am building a model from scratch and I see this error after version 3.9.0 for some datasets. I can send you guys a sample dataset through our Meta marketing science partner for the debug if it helps

**Comment by laresbernardo** [comment] 2023-05-11 20:59
Hi @sahbakn, please do. That will help us debug and understand what's happening in your specific case. Thanks!

**Comment by laresbernardo** [comment] 2023-05-12 13:45
@SeanRichterWalsh not sure that's actually the case here. What version are you on? 
Note that in the demo we set "events" which is a character column as one of the variables in "context_vars". When doing that, Robyn automatically detects this and sets it as one of the "factor_vars" event hough the user doesn't manually do that. That behavior is actually printed as a message for you the user to know:
> Automatically set these variables as 'factor_vars': 'events'
Also keep in mind that this message won't show up if you add `robyn_inputs(..., factor_vars = "events", ...`)
If you have a reproducible example and are using the latest dev version, please do share it in another ticket given I don't think these are related with the information provided @SeanRichterWalsh

**Comment by SeanRichterWalsh** [comment] 2023-05-12 14:22
Thanks @laresbernardo . Yes, I am using the latest dev version. I restarted my R session and tried again with my dataset and it seems to work fine now. My own data set's events variable is now being auto-forced to factor as expected and I don't have to explicitly use the factor_vars argument. Not sure what was up earlier. Thanks.

**Comment by TrunckYagora** [comment] 2023-05-15 13:42
Hi, 

we're running into the same issue with both version 3.9 and 3.10: `task 1 failed - "arguments imply differing number of rows: 6, 7"`
Has there been an update on this issue yet?

**Comment by laresbernardo** [comment] 2023-05-15 14:09
Hi @TrunckYagora we haven't been able to replicate this issue yet. Can you please provide a reproducible example that returns that error so it can help us debug?

**Comment by arturodz** [comment] 2023-05-15 15:15
Interesting point. This might have happened to me as well. I will do some tests tomorrow see if I can reproduce that error with those circumstance. Will circle back if so.

**Comment by laresbernardo** [comment] 2023-05-15 15:56
YES! That was it. We actually checked for no variance on raw input data before running `robyn_engineering()` and not afterwards. Now I've just fixed this issue by checking both and returning meaningful and helpful errors. Can any of you update and validate it's fixed on latest dev version? Thanks for the valuable hint @SeanRichterWalsh

**Comment by sahbakn** [comment] 2023-05-15 17:33
@laresbernardo I looked into my data and during the modeling time frame that I was getting the error, I had one variable with 0 variance, fixing that I do not see the error anymore!

**Comment by SeanRichterWalsh** [comment] 2023-05-15 19:05
> YES! That was it. We actually checked for no variance on raw input data before running `robyn_engineering()` and not afterwards. Now I've just fixed this issue by checking both and returning meaningful and helpful errors. Can any of you update and validate it's fixed on latest dev version? Thanks for the valuable hint @SeanRichterWalsh

Oh great! A silly mistake on my part but I am glad it has helped lead to a resolution here. I can confirm that the latest dev version gives a very informative message when a variable has zero variance. Thanks a lot.

<img width="856" alt="image" src="https://github.com/facebookexperimental/Robyn/assets/42702165/33f67016-8441-4151-b1ba-10bfe1b58a27">

**Comment by laresbernardo** [comment] 2023-05-15 19:08
Great! Thanks for confirming. I'll check with @richa-makhija and @dmacoritto as well! This should have fixed the issue for everyone. Will close ticket after a week or confirmation.

**Comment by TrunckYagora** [comment] 2023-05-16 08:55
Hi @laresbernardo, 

thanks for the update, interestingly enough we're receive the error even when we're running the model without the factor_vars. You can find the data we're using to reproduce the error here: 
[mockup_data.csv](https://github.com/facebookexperimental/Robyn/files/11485907/mockup_data.csv)

The code is as follows: 

```
data("dt_prophet_holidays")
head(dt_prophet_holidays)
selected_dt <- read.csv("/Users/Tim_Runck/Documents/data/ysabal/mockup_data.csv")

InputCollect <- robyn_inputs(
  dt_input = selected_dt,
  dt_holidays = dt_prophet_holidays,
  date_var = "date", # date format must be "2020-01-01"
  dep_var = "Umsatz", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "season", "holiday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "DE", # input one country. dt_prophet_holidays includes 59 countries by default
  paid_media_spends = c("cost_dv360", "cost_fb_insta", "cost_pinterest"), # mandatory input
  paid_media_vars = c("impression_dv360", "impression_fb_insta", "impression_pinterest"), # mandatory.
  # paid_media_vars must have same order as paid_media_spends. Use media exposure metrics like
  # impressions, GRP etc. If not applicable, use spend instead.
  # organic_vars = "events", # marketing activity without media spend
  # factor_vars = c("events"), # force variables in context_vars or organic_vars to be categorical
  # window_start = min(selected_dt$date),
  # window_end = max(selected_dt$date),
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf.
)
print(InputCollect)

hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)
# plot_adstock(plot = TRUE)
# plot_saturation(plot = TRUE)
hyper_limits()

# Example hyperparameters ranges for Geometric adstock
hyperparameters <- list(
  cost_dv360_alphas = c(0.5, 3),
  cost_dv360_gammas = c(0.3, 1),
  cost_dv360_thetas = c(0, 0.3),
  cost_fb_insta_alphas = c(0.5, 3),
  cost_fb_insta_gammas = c(0.3, 1),
  cost_fb_insta_thetas = c(0.1, 0.4),
  cost_pinterest_alphas = c(0.5, 3),
  cost_pinterest_gammas = c(0.3, 1),
  cost_pinterest_thetas = c(0.3, 0.8),
  train_size = c(0.3, 0.8)
)

InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)
print(InputCollect)

OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, # NULL defaults to (max available - 1)
  iterations = 2000, # 2000 recommended for the dummy dataset with no calibration
  trials = 5, # 5 recommended for the dummy dataset
  ts_validation = TRUE, # 3-way-split time series for NRMSE validation.
  add_penalty_factor = FALSE # Experimental feature. Use with caution.
)
print(OutputModels)
```

**Comment by TrunckYagora** [comment] 2023-05-17 05:31
Hi @laresbernardo 

awesome - thank you very much for your support. In the latest dev version I get the error message you mentioned and we can run Robyn as usual with the correct parameters.

**Closed** 2023-05-17 17:04 UTC
Labels: bug
