### ISSUE TITLE
response increased 8 times and the points got out of the response curve

### ISSUE THREAD

**Issue by Eberland** [facebookexperimental/Robyn#301] opened 2022-02-10 14:24 UTC
## Issue
In version 3.5.1, a bug appeared: response increased 8 times and the points got out of the response curve.
![Screenshot_20220210_172245](https://user-images.githubusercontent.com/5735108/153427150-da41a7d2-e2f9-4354-80b9-835b5db107e2.png)
## Model configuration
set.seed(122)
InputCollect <- robyn_inputs(
  dt_input = dt_simulated_weekly
  ,dt_holidays = dt_prophet_holidays
  ,date_var = "af_date"
  ,dep_var = "revenue"
  ,dep_var_type = "conversion"
  ,prophet_vars = c("trend", "season",  "holiday")
  ,prophet_signs = c("default", "default",  "default")
  ,prophet_country = "RU"
  ,paid_media_vars = paid_media_vars
  ,paid_media_spends = cols[grepl("_s$", cols)]
  , context_vars = c("gmv","total_orders")
  ,context_signs = c("positive", "positive")
  ,cores = 30
  ,adstock = "geometric"
  ,iterations = 2000
  ,nevergrad_algo = "TwoPointsDE"
  ,trials = 5
  ,hyperparameters = hyperparameters
)

OutputCollect <- robyn_run(
  InputCollect = InputCollect
  , plot_folder = robyn_object
  , pareto_fronts = 3
  , plot_pareto = TRUE
)

AllocatorCollect <- robyn_allocator( 
  InputCollect = InputCollect
  , OutputCollect = OutputCollect
  , optim_algo ="MMA_AUGLAG"
  , select_model = i
  , scenario = "max_response_expected_spend"
  , channel_constr_low = c(  0.5,    0.5,    0.8,    0.5)
  , channel_constr_up =  c(  2.5,    2,      1.2,    2.5)
  , expected_spend = 45816000 
  , expected_spend_days = 28
)

## Environment & Robyn version
R version 4.1.2
Robyn version 3.5.1

**Comment by gufengzhou** [comment] 2022-02-10 16:39
Hi, this is strange. I've just tried it out with our sample data and it looks fine. Have you restarted R session after installing the packge? I notice you're using "MMA_AUGLAG" while our default is SLSQP. Have you tried tthat too?

**Comment by Eberland** [comment] 2022-02-11 08:22
Nope(, SLSQP and restarting session didn't help

**Comment by gufengzhou** [comment] 2022-02-11 08:27
Are your paid_media_vars and paid_media_spends in same order?

**Comment by Eberland** [comment] 2022-02-11 08:36
Of course

**Comment by gufengzhou** [comment] 2022-02-11 08:46
Then I'd need a reproducible dataset to replicate this error and debug. Please mask your real value. 

I also see you use revenue as dep_var but declare it as conversion? That's unusual. Also you're using gmv & total_orders as context_vars? If they're what the names say, then it's also unusual, because orders and gmv are strong confounders to revenue.

**Comment by Eberland** [comment] 2022-02-11 09:00
revenue is just a name, actually it's conversion
if I delete gmv & total_orders nothing will change, so it also doesn't affect
I'll send you data a bit later, after preparing it

**Comment by gufengzhou** [comment] 2022-02-11 09:08
thanks, I'd also need the holidays dataframe in case you've changed it as well as your hyperparameters definition.

**Comment by Eberland** [comment] 2022-02-11 09:23
[data.csv](https://github.com/facebookexperimental/Robyn/files/8047372/data.csv)
script:
`library(Robyn)
library(reticulate)
set.seed(122)

Sys.setenv(R_FUTURE_FORK_ENABLE="true")
options(future.fork.enable = TRUE)

# load data
dt_simulated_weekly <- read.table("~/data.csv", header=T, sep=";")
data("dt_prophet_holidays")
robyn_object <- "~/MyRobyn.RDS"

# params init
cols <- colnames(dt_simulated_weekly)
paid_media_vars <- cols[grepl("_i$", cols)]
hyperparameters <-list(

  bytedanceglobal_int_i_alphas = c(0.5, 3),
  bytedanceglobal_int_i_gammas = c(0.3, 1),
  bytedanceglobal_int_i_thetas = c(0.19, 0.27),

  facebook.ads_i_alphas = c(0.5, 3),
  facebook.ads_i_gammas = c(0.3, 1),
  facebook.ads_i_thetas = c(0.33, 0.42),

  google.ads.uac_i_alphas = c(0.5, 3),
  google.ads.uac_i_gammas = c(0.3, 1),
  google.ads.uac_i_thetas = c(0.21, 0.25),

  yandexdirect_int_i_alphas = c(0.5, 3),
  yandexdirect_int_i_gammas = c(0.3, 1),
  yandexdirect_int_i_thetas = c(0.19, 0.25)
)

# model init
InputCollect <- robyn_inputs(
  dt_input = dt_simulated_weekly
  ,dt_holidays = dt_prophet_holidays
  ,date_var = "af_date"
  ,dep_var = "revenue"
  ,dep_var_type = "conversion"
  ,prophet_vars = c("trend", "season",  "holiday")
  ,prophet_signs = c("default", "default",  "default")
  ,prophet_country = "RU"
  ,paid_media_vars = paid_media_vars
  ,paid_media_spends = cols[grepl("_s$", cols)]
  ,cores = 30
  ,adstock = "geometric"
  ,iterations = 2000
  ,nevergrad_algo = "TwoPointsDE"
  ,trials = 5
  ,hyperparameters = hyperparameters
)

OutputCollect <- robyn_run(
  InputCollect = InputCollect
  , plot_folder = robyn_object
  , pareto_fronts = 3
  , plot_pareto = TRUE
)

pngs <- OutputCollect$clusters$models$solID
{for(i in pngs)
{AllocatorCollect <- robyn_allocator(
  InputCollect = InputCollect
  , OutputCollect = OutputCollect
  , optim_algo ="SLSQP_AUGLAG"
  , select_model = i
  , scenario = "max_response_expected_spend"
  , channel_constr_low = c(  0.5,    0.5,    0.8,    0.5)
  , channel_constr_up =  c(  2.5,    2,      1.2,    2.5)
  , expected_spend = 45816000
  , expected_spend_days = 28
)

robyn_object <- paste(OutputCollect$plot_folder,i,'.RDS',sep='')
robyn_save(robyn_object = robyn_object
           , select_model = i
           , InputCollect = InputCollect
           , OutputCollect = OutputCollect
)
}
}`

**Comment by gufengzhou** [comment] 2022-02-14 12:31
Hi, just pushed a fix on this. Please update the package and try.

**Closed** 2022-02-14 17:19 UTC
