### ISSUE TITLE
Robyn does not work on Databricks notebooks

### ISSUE THREAD

**Issue by danzafar** [facebookexperimental/Robyn#108] opened 2021-07-07 22:50 UTC
# Contributing to FB NextGen MMM R script

# Issue

Robyn does not work on Databricks notebooks. Due to this line:

https://github.com/facebookexperimental/Robyn/blob/master/source/fb_robyn.func.R#L1023

`closeAllConnections()` will close the socket that sends data to/from R REPL stdout/stderr and the Notebook.

I mitigated the issue by simply omitting the line before sourcing that script:
```
%sh
sed -i /closeAllConnections/d ~/robyn/source/fb_robyn.func.R
```

Here are the connections that exist by default in the notebooks:
```
> showConnections()
  description         class      mode text     isopen   can read can write
3 "->localhost:36985" "sockconn" "a+" "text"   "opened" "yes"    "yes"    
4 "->localhost:36263" "sockconn" "a+" "text"   "opened" "yes"    "yes"    
5 "->localhost:35161" "sockconn" "wb" "binary" "opened" "yes"    "yes"   
```
As long as these are not deleted, it will work.

# Steps to Reproduce

Running any minimal version of `f.robyn()` fails. You can replicate the issue by just running the problematic line:

`closeAllConnections()`

# Expected Behavior

It would be nice for Databricks users to be able to experiment with Robyn.

# Actual Results

After running the problematic code, any subsequent notebook operations yeild:
```
[Fetch Stdout Timeout]
Error in writeLines(DB_STREAM_BEACON_STRING_END__, DATABRICKS_STDOUTCONNSTREAM__) : 
  invalid connection
Some(<code style = 'font-size:10p'>  </code>)
```

# Environment

R version: 4.0.4, DBR 8.3 ML.

**Comment by gufengzhou** [comment] 2021-07-09 11:47
Hi, thanks for raising this. To be honest I have no experience with databricks. We'll see how to avoid closing all connections and change it in the next update.

**Comment by le1tz3y** [comment] 2021-07-16 18:21
I am facing the same issue as described by @danzafa. I tried removing `closeAllConnections ()` before sourcing, but I am still seeing the error.

**Comment by danzafar** [comment] 2021-07-20 15:40
@gufengzhou - can you link the PR that fixed this? Otherwise, it is disingenuous to close out the issue.

**Comment by gufengzhou** [comment] 2021-07-22 08:12
Hey guys, my mac is crashing with your fix with makeCluster and closeCluster. I'm asking others to try it out too. Would you  please recheck your fix for non-databricks environment? Also have you tried doParallel::stopImplicitCluster() ?

**Comment by gufengzhou** [comment] 2021-07-22 13:44
After updating R to 4.1.0 I got makeCluster running without crashing. But it's significantly slower than just doing registerDoParallel(set_cores).

**Comment by danzafar** [comment] 2021-07-22 21:24
Do you have the wrong issue? This commit will not solve this issue since `closeAllConnections()` is still present:
https://github.com/AnisLEBIK/Robyn/blob/master/source/fb_robyn.func.R#L1023

**Comment by gufengzhou** [comment] 2021-07-26 10:08
oh you're right. sorry for that. actually we'll need to find a way to only close specific connections correctly instead of all, which is bit difficult to do because we don't run it on databricks. I'll leave it open to solve it later

**Comment by AnisLEBIK** [comment] 2021-07-26 10:14
Hello everybody.

Initially, I had opened a PR to fix the R session crash issue that happens after launching a 2nd modeling in a row.
 Indeed, as you can see in the screenshot, using the old code (before adding makeCluster ()/closeCluster), the R sessions crashes when the 2nd modeling reaches the optimum pareto plotting stage.

<img width="951" alt="R Session Aborted" src="https://user-images.githubusercontent.com/86845757/126971960-56a50cb2-5e3c-478c-9dd6-1bfca166dc76.PNG">

I realized that this bug was linked to a bad closing of the parallelization at the end of the modeling. Also, restarting the R session after the 1st modeling displayed several similar error messages in a row : **Error in summary.connection (connection): incorrect connection**. This error is due to a bad closing of the parallelization.

<img width="647" alt="R session restart" src="https://user-images.githubusercontent.com/86845757/126972005-a612629e-014a-43d1-81c4-3d90ef445843.PNG">

The primary goal of my Pull Request was therefore to correctly close the parallelization and thus allow modeling several times in a row, through a loop or manually.
In addition, when we restart the sessions with the modification made, the R session is restarted correctly without displaying an error message.
Finally the closeAllConnections () line can be removed without causing any problem to the code.

**Comment by gufengzhou** [comment] 2021-07-26 10:21
Hey @AnisLEBIK , thanks for commenting this. Sorry that I've just reversed the commit because we realised that makeCluster slows down the parallel performance quite a lot because it makeCluster forces the SNOW backend that is rather for windows, as I understood here [https://stackoverflow.com/questions/28829300/doparallel-cluster-vs-cores](url). Also, registerDoParallel() is supposed to choose between OS automatically according to this thread? I'll re-merge it when we can find a more universal solution.

**Closed** 2021-10-19 11:58 UTC

**Comment by danzafar** [comment] 2021-10-19 15:39
@gufengzhou , why is this closed? Can you please link to the PR that solves this issue? If there is none, please keep it open.

**Comment by andrey-legayev** [comment] 2021-11-19 16:03
Hi all,

I see that the ticket is closed already, just want to add my findings:

I've found significant difference in performance of doParallel vs. doFuture:
 - Mac / Linux - doParallel works 20-25% faster
 - Windows - 9% faster (less overhead?)
 
This is very significant difference when you run Robyn for several countries with iterations=2000, trials=5
It can easily result in 1 hour time savings per work day for those who run it often.
I understand that in past this backend caused different issues for you, but still, it's a big performance difference.

I've prepared pull request which switches code to doParallel: #222 
I benchmarked it on Win/Lin/Mac - works everywhere, works faster
I also ran it in RStudio on Mac - no issues mentioned above were observed. 

Could you try to reproduce old issues in RStudio which you had in past ?

### Compatibility issues and why this time it should work fine
doParallel() can work with pre-created cluster or with implicitly created cluster.
If you created cluster via makeCluster() then it creates it as SNOW by default (or you can create any other type of cluster).

But if you use ```registerDoParallel(4)``` then it has different behavior:
 - for Unix-OS: it creates cluster via doParallelMC (==> multicore / multi-thread)
 - for Windows: it creates SNOW cluster (==> multi-process / multi-sessions)

My version is a bit different from versions referenced in this thread above:
 - Linux / Mac - doParallel creates cluster via doParallelMC, SNOW is not used
 - Windows - no cluster created, it works in sequential way
